name: flutter_mvvm_architecture
description: "Project to demonstrate the basics of my preferred architecture for Flutter projects"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: 6.1.2
  flutter_bloc: 8.1.6
  go_router: 14.1.4
  uuid: 4.4.0

  # Code generators
  json_annotation: 4.9.0
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

  # Code generators
  build_runner: 2.4.11
  json_serializable: 6.8.0
  freezed: 2.5.2

flutter:
  uses-material-design: true
